In [4]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("C:/Users/Piyara/Desktop/Child Mortality Dashboard/Data/Raw/CME (1).csv")

In [10]:
df.head()

,REF_AREA,Geographic area,INDICATOR,Indicator,SEX,Sex,WEALTH_QUINTILE,Wealth Quintile,DATA_SOURCE,COUNTRY_NOTES,UNIT_MEASURE,Unit of measure,TIME_PERIOD,OBS_VALUE,REF_PERIOD,LOWER_BOUND,UPPER_BOUND,OBS_STATUS,Observation Status
0,AFG,Afghanistan,CME_MRY1T4,Child mortality rate (aged 1-4 years),F,Female,_T,Total,UN_IGME,NaN,D_PER_1000_1,"Deaths per 1,000 children aged 1",1957,147.274731,NaN,109.177829,201.078717,A,Normal value
1,AFG,Afghanistan,CME_MRY1T4,Child mortality rate (aged 1-4 years),F,Female,_T,Total,UN_IGME,NaN,D_PER_1000_1,"Deaths per 1,000 children aged 1",1958,142.905242,NaN,109.189468,189.721951,A,Normal value
2,AFG,Afghanistan,CME_MRY1T4,Child mortality rate (aged 1-4 years),F,Female,_T,Total,UN_IGME,NaN,D_PER_1000_1,"Deaths per 1,000 children aged 1",1959,138.735513,NaN,108.819147,179.755033,A,Normal value
3,AFG,Afghanistan,CME_MRY1T4,Child mortality rate (aged 1-4 years),F,Female,_T,Total,UN_IGME,NaN,D_PER_1000_1,"Deaths per 1,000 children aged 1",1960,134.779641,NaN,108.502122,170.765277,A,Normal value
4,AFG,Afghanistan,CME_MRY1T4,Child mortality rate (aged 1-4 years),F,Female,_T,Total,UN_IGME,NaN,D_PER_1000_1,"Deaths per 1,000 children aged 1",1961,131.253224,NaN,107.492955,163.152389,A,Normal value

In [12]:
df.shape

(44421, 19)

In [14]:
df.columns

Index(['REF_AREA', 'Geographic area', 'INDICATOR', 'Indicator', 'SEX', 'Sex',
       'WEALTH_QUINTILE', 'Wealth Quintile', 'DATA_SOURCE', 'COUNTRY_NOTES',
       'UNIT_MEASURE', 'Unit of measure', 'TIME_PERIOD', 'OBS_VALUE',
       'REF_PERIOD', 'LOWER_BOUND', 'UPPER_BOUND', 'OBS_STATUS',
       'Observation Status'],
      dtype='object')

In [16]:
df.columns.tolist()

['REF_AREA',
 'Geographic area',
 'INDICATOR',
 'Indicator',
 'SEX',
 'Sex',
 'WEALTH_QUINTILE',
 'Wealth Quintile',
 'DATA_SOURCE',
 'COUNTRY_NOTES',
 'UNIT_MEASURE',
 'Unit of measure',
 'TIME_PERIOD',
 'OBS_VALUE',
 'REF_PERIOD',
 'LOWER_BOUND',
 'UPPER_BOUND',
 'OBS_STATUS',
 'Observation Status']

In [18]:
for col in df.columns:
    print(col)

REF_AREA
Geographic area
INDICATOR
Indicator
SEX
Sex
WEALTH_QUINTILE
Wealth Quintile
DATA_SOURCE
COUNTRY_NOTES
UNIT_MEASURE
Unit of measure
TIME_PERIOD
OBS_VALUE
REF_PERIOD
LOWER_BOUND
UPPER_BOUND
OBS_STATUS
Observation Status

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44421 entries, 0 to 44420
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   REF_AREA            44421 non-null  object
 1   Geographic area     44421 non-null  object
 2   INDICATOR           44421 non-null  object
 3   Indicator           44421 non-null  object
 4   SEX                 44421 non-null  object
 5   Sex                 44421 non-null  object
 6   WEALTH_QUINTILE     44421 non-null  object
 7   Wealth Quintile     44421 non-null  object
 8   DATA_SOURCE         44421 non-null  object
 9   COUNTRY_NOTES       1399 non-null   object
 10  UNIT_MEASURE        44421 non-null  object
 11  Unit of measure     44421 non-null  object
 12  TIME_PERIOD         44421 non-null  int64
 13  OBS_VALUE           44421 non-null  float64
 14  REF_PERIOD          0 non-null      float64
 15  LOWER_BOUND         44421 non-null  float64
 16  UPPER_BOUND         44421 non-null  float64
 17  OBS_STATUS          43791 non-null  object
 18  Observation Status  43791 non-null  object
dtypes: float64(4), int64(1), object(14)
memory usage: 6.4+ MB

In [22]:
df.dtypes

REF_AREA               object
Geographic area        object
INDICATOR              object
Indicator              object
SEX                    object
Sex                    object
WEALTH_QUINTILE        object
Wealth Quintile        object
DATA_SOURCE            object
COUNTRY_NOTES          object
UNIT_MEASURE           object
Unit of measure        object
TIME_PERIOD             int64
OBS_VALUE             float64
REF_PERIOD            float64
LOWER_BOUND           float64
UPPER_BOUND           float64
OBS_STATUS             object
Observation Status     object
dtype: object

In [24]:
df.isnull().sum()

REF_AREA                  0
Geographic area           0
INDICATOR                 0
Indicator                 0
SEX                       0
Sex                       0
WEALTH_QUINTILE           0
Wealth Quintile           0
DATA_SOURCE               0
COUNTRY_NOTES         43022
UNIT_MEASURE              0
Unit of measure           0
TIME_PERIOD               0
OBS_VALUE                 0
REF_PERIOD            44421
LOWER_BOUND               0
UPPER_BOUND               0
OBS_STATUS              630
Observation Status      630
dtype: int64

In [26]:
df.duplicated().sum()

0

In [28]:
df_clean = df[[
    "Geographic area",
    "Indicator",
    "Sex",
    "Wealth Quintile",
    "DATA_SOURCE",
    "COUNTRY_NOTES",
    "Unit of measure",
    "TIME_PERIOD",
    "OBS_VALUE",
    "LOWER_BOUND",
    "UPPER_BOUND",
    "Observation Status"
]].copy()

In [30]:
df_clean = df_clean.rename(columns={
    "Geographic area": "country",
    "Indicator": "indicator",
    "Sex": "sex",
    "Wealth Quintile": "wealth quintile",
    "DATA_SOURCE": "data source",
    "COUNTRY_NOTES": "country notes",
    "Unit of measure": "unit measure",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "obs value",
    "LOWER_BOUND": "lower bound",
    "UPPER_BOUND": "upper bound",
    "Observation Status": "observation status"
})

In [32]:
df_clean = df_clean.dropna(subset=["country", "indicator", "year", "obs value"])

In [34]:
text_cols = ["country", "indicator", "sex", "wealth quintile", "data source", "unit measure", "observation status"]

for col in text_cols:
    df_clean[col] = df_clean[col].apply(lambda x: x.strip() if isinstance(x, str) else x)

In [36]:
numeric_cols = ["year", "obs value", "lower bound", "upper bound"]

for col in numeric_cols:
    df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")

In [38]:
df_clean["year"] = df_clean["year"].astype(int)

In [40]:
(df_clean["obs value"] < 0).sum()

0

In [42]:
df_clean["sex"].value_counts(dropna=False)

sex
Total     14941
Female    14740
Male      14740
Name: count, dtype: int64

In [44]:
df_clean["wealth quintile"].value_counts(dropna=False)

wealth quintile
Total    44421
Name: count, dtype: int64

In [46]:
df_clean["indicator"].value_counts(dropna=False)

indicator
Child mortality rate (aged 1-4 years)    44421
Name: count, dtype: int64

In [48]:
df_clean["country"].nunique()

249

In [50]:
df_clean["data source"].value_counts(dropna=False)

data source
UN_IGME    44421
Name: count, dtype: int64

In [52]:
df_clean.head()

,country,indicator,sex,wealth quintile,data source,country notes,unit measure,year,obs value,lower bound,upper bound,observation status
0,Afghanistan,Child mortality rate (aged 1-4 years),Female,Total,UN_IGME,NaN,"Deaths per 1,000 children aged 1",1957,147.274731,109.177829,201.078717,Normal value
1,Afghanistan,Child mortality rate (aged 1-4 years),Female,Total,UN_IGME,NaN,"Deaths per 1,000 children aged 1",1958,142.905242,109.189468,189.721951,Normal value
2,Afghanistan,Child mortality rate (aged 1-4 years),Female,Total,UN_IGME,NaN,"Deaths per 1,000 children aged 1",1959,138.735513,108.819147,179.755033,Normal value
3,Afghanistan,Child mortality rate (aged 1-4 years),Female,Total,UN_IGME,NaN,"Deaths per 1,000 children aged 1",1960,134.779641,108.502122,170.765277,Normal value
4,Afghanistan,Child mortality rate (aged 1-4 years),Female,Total,UN_IGME,NaN,"Deaths per 1,000 children aged 1",1961,131.253224,107.492955,163.152389,Normal value

In [54]:
df_clean["year"].min(), df_clean["year"].max()

(1930, 2024)

In [56]:
df_clean["unit measure"].value_counts(dropna=False)

unit measure
Deaths per 1,000 children aged 1    43791
Deaths per 1,000 live births          630
Name: count, dtype: int64

In [58]:
df_clean["observation status"].value_counts(dropna=False)

observation status
Normal value    43791
NaN               630
Name: count, dtype: int64

In [60]:
df_clean = df_clean[df_clean["unit measure"] == "Deaths per 1,000 children aged 1"]

In [62]:
df_clean["unit measure"].value_counts(dropna=False)

unit measure
Deaths per 1,000 children aged 1    43791
Name: count, dtype: int64

In [64]:
df_clean["observation status"].value_counts(dropna=False)

observation status
Normal value    43791
Name: count, dtype: int64

In [66]:
df_clean.shape

(43791, 12)

In [68]:
df_clean.isnull().sum().sort_values(ascending=False)

country notes         42392
country                   0
indicator                 0
sex                       0
wealth quintile           0
data source               0
unit measure              0
year                      0
obs value                 0
lower bound               0
upper bound               0
observation status        0
dtype: int64

In [70]:
df_clean = df_clean.drop(columns=["country notes"])

In [72]:
df_clean.columns

Index(['country', 'indicator', 'sex', 'wealth quintile', 'data source',
       'unit measure', 'year', 'obs value', 'lower bound', 'upper bound',
       'observation status'],
      dtype='object')

In [74]:
df_clean = df_clean.drop(columns=[
    "indicator",
    "wealth quintile",
    "data source",
    "unit measure",
    "observation status"
])

In [76]:
df_clean.columns

Index(['country', 'sex', 'year', 'obs value', 'lower bound', 'upper bound'], dtype='object')

In [78]:
df_clean.head()

       country     sex  year   obs value  lower bound  upper bound
0  Afghanistan  Female  1957  147.274731   109.177829   201.078717
1  Afghanistan  Female  1958  142.905242   109.189468   189.721951
2  Afghanistan  Female  1959  138.735513   108.819147   179.755033
3  Afghanistan  Female  1960  134.779641   108.502122   170.765277
4  Afghanistan  Female  1961  131.253224   107.492955   163.152389

In [80]:
df_clean.to_csv("../data/cleaned/cme_cleaned.csv", index=False)